begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select plan(34);
select is(has_schema_privilege('anon','app_private','USAGE'), false, 'guest has no private schema usage');
select is(has_schema_privilege('authenticated','app_private','USAGE'), false, 'account has no private schema usage');
select is(has_table_privilege('authenticated','app_private.checkins','SELECT'), false, 'accounts cannot directly read raw check-ins');
select is(has_table_privilege('authenticated','app_private.checkins','INSERT'), false, 'accounts cannot directly insert raw check-ins');
select is(has_function_privilege('anon','public.bootstrap_profile(uuid)','EXECUTE'), false, 'guest cannot bootstrap');
select is(has_function_privilege('authenticated','public.bootstrap_profile(uuid)','EXECUTE'), true, 'account can invoke checked bootstrap');
select is(has_function_privilege('anon','public.mutate_checkin(jsonb)','EXECUTE'), false, 'guest cannot execute mutations');
select is(has_function_privilege('authenticated','public.mutate_checkin(jsonb)','EXECUTE'), true, 'account can invoke checked mutations');
select is(has_function_privilege('anon','public.pull_changes(text,integer)','EXECUTE'), false, 'guest cannot pull private history');
select is(has_function_privilege('authenticated','public.pull_changes(text,integer)','EXECUTE'), true, 'account can invoke checked pull');
select is(has_function_privilege('anon','public.list_regions(text,text,text,integer)','EXECUTE'), true, 'guest can browse public directory');
select is(has_function_privilege('authenticated','public.resolve_region(text)','EXECUTE'), true, 'account can resolve broad regions');
select is(has_table_privilege('anon','app_private.regions','SELECT'), false, 'guest cannot directly read private schema tables');
select is(has_table_privilege('authenticated','app_private.directory_versions','INSERT'), false, 'account cannot replace the directory');
select is(has_function_privilege('anon','public.update_profile(jsonb)','EXECUTE'), false, 'guest cannot change consent');
select is(has_function_privilege('authenticated','public.update_profile(jsonb)','EXECUTE'), true, 'account can invoke checked consent changes');
select is(has_function_privilege('anon','public.read_club(text,text,integer)','EXECUTE'), true, 'guest can read sanitized eligible feed');
select is(has_table_privilege('anon','app_private.server_secrets','SELECT'), false, 'guest cannot read cursor keys');
select is(has_function_privilege('anon','public.block_user(jsonb)','EXECUTE'), false, 'guest cannot block');
select is(has_function_privilege('authenticated','public.report_subject(jsonb)','EXECUTE'), true, 'account can invoke checked reporting');
select is(has_table_privilege('authenticated','app_private.staff_members','INSERT'), false, 'account cannot promote itself');
select is(has_table_privilege('authenticated','app_private.reports','SELECT'), false, 'account cannot read other reports');
select is(has_function_privilege('authenticated','app_private.require_staff()','EXECUTE'), false, 'private staff authorization helper is not exposed');
select is((select count(*)::integer from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='app_private' and c.relkind='r' and not c.relrowsecurity), 0, 'all private tables enable RLS');
select is(has_function_privilege('anon','public.preview_invite(text)','EXECUTE'), false, 'guest cannot enumerate invitations');
select is(has_function_privilege('authenticated','public.join_circle(jsonb)','EXECUTE'), true, 'account can invoke checked joins');
select is(has_function_privilege('authenticated','public.read_circle_today(uuid)','EXECUTE'), true, 'account can invoke checked circle reads');
select is(has_function_privilege('authenticated','app_private.circle_today(uuid,uuid,timestamptz)','EXECUTE'), false, 'account cannot spoof a circle viewer');
select is(has_function_privilege('authenticated','app_private.invite_code(uuid,uuid,uuid)','EXECUTE'), false, 'account cannot derive invitation secrets');
select is(has_table_privilege('authenticated','app_private.circle_memberships','INSERT'), false, 'account cannot bypass membership limits');
select is(has_function_privilege('anon','public.request_account_deletion(jsonb)','EXECUTE'), false, 'deletion initiation requires a verified account');
select is(has_function_privilege('anon','public.account_deletion_status(text)','EXECUTE'), true, 'status proof remains usable after Auth removal');
select is(has_function_privilege('authenticated','app_private.advance_deletion(uuid)','EXECUTE'), false, 'clients cannot run privileged cleanup');
select is(has_function_privilege('anon','public.export_account(uuid,text,integer)','EXECUTE'), false, 'guests cannot export accounts');
select * from finish();
rollback;
